---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: upgrade
    apt:
      upgrade: dist

  - name: install essentials
    apt:
      name: 
        - fdupes
      state: latest
      # state: absent
      update_cache: yes
